
name: dv_photo_app
description: DV-ready photo cropper (Global + Ethiopia flavors) — Part 1 scaffold
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^16.1.0

  # For future parts
  # image: ^4.1.7
  # image_picker: ^1.1.2
  # path_provider: ^2.1.4
  # intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
